-- Brings an existing database up to date for assignment flags, version conflicts and delegations (user story 21).
-- Hibernate's "update" cannot add NOT NULL columns to a table that already has rows, so run this once.
-- Safe to run more than once.

BEGIN;

ALTER TABLE assignments ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 0;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS is_flagged boolean NOT NULL DEFAULT false;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS missing_employee_count integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS assignment_delegations (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id        bigint                      NOT NULL REFERENCES assignments (id),
    employee_id          bigint                      NOT NULL REFERENCES users (id),
    delegated_by_user_id bigint                      NOT NULL,
    delegated_by         varchar(255)                NOT NULL,
    delegated_at         timestamp(6) with time zone NOT NULL,
    CONSTRAINT assignment_delegations_assignment_employee_key UNIQUE (assignment_id, employee_id)
);

COMMIT;
