### 0. Login to get token
# @name login
POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "email": "1@1.dk",
  "password": "123"
}
### Store the token from the response
@authToken = {{login.response.body.token}}


### 1. Get All Assignments (with Token)
GET http://localhost:7070/api/assignment/all
Authorization: Bearer {{authToken}}


### 2. Create a new Assignment
POST http://localhost:7070/api/assignment
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Homework",
  "isActive": true
}


### 3. Update Assignment
PUT http://localhost:7070/api/assignment/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Updated Homework Name",
  "isActive": true
}


### 4. Deactivate Assignment
PATCH http://localhost:7070/api/assignment/1/deactivate
Authorization: Bearer {{authToken}}


### 5. Hard Delete Assignment
DELETE http://localhost:7070/api/assignment/1
Authorization: Bearer {{authToken}}